on:
 push:
    branches:
      - main
jobs:
 build:
   runs-on: ubuntu-latest
   name: to deploy react app
   
   steps:
      
    - name: checkout
      uses: actions/checkout@v1

      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.10.0
          
    - name: Build React App
      uses: virtuecloud/Composite-actions/Build/Node@main
      
    - name: Deploy app build to S3 bucket
      uses: virtuecloud/Composite-actions/Deploy/S3@main
      with:
         BUCKET_NAME: ${{ secrets.Bucket }}
         PATH: build/         # path of the file or folder to be uploaded on S3
         
    - name:  Invalidate cache
      uses: virtuecloud/Composite-actions/Deploy/Cloudfront@main
      with:
         AWS_DISTRIBUTION_ID: ${{ secrets.Cloudfront_distribution_ID }}
